### ISSUE TITLE
Add support for chrome options

### ISSUE THREAD

**Issue by SergeyPirogov** [SergeyPirogov/kirk#36]
-- headless --disable-gpu

**Comment by SergeyPirogov** [comment]
kirk.chrome.args = headless, disable-gpu
kirk.chrome.binary = /home

**Comment by SergeyPirogov** [comment]
https://github.com/SergeyPirogov/kirk/pull/37#pullrequestreview-52387136

**Comment by erdelyizsolt** [comment]
Dear Sergey, hy,
 it does not work with chrome version 78...
is there anything that I miss? 👍 
java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments(Ljava/util/List;)
Thanks!

**Comment by SergeyPirogov** [comment]
Probably no.
