### ISSUE TITLE
toString() for select element should be element text

### ISSUE THREAD

**Issue by ArtyomAnohin** [SergeyPirogov/kirk#66]
https://github.com/SergeyPirogov/kirk/blob/1b275bf5594f7751e0b2f60eebd50d56ce0aadaf/kirk-core/src/main/kotlin/com/automation/remarks/kirk/core/support.kt#L48

`return element.text`

**Comment by SergeyPirogov** [comment]
No, ```toString()``` should return element locator. Existing implementation is correct
